name: Publish Workflow
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup_nodejs
        name: Setup node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - id: npm_ci
        name: npm ci
        run: npm ci
      - id: publish
        name: Publish
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
